spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_authority_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

#redis配置文件
  redis:
    port: 6379
    host: 192.168.112.100
    database: 0
    client-type: lettuce
    lettuce:
      pool:
        max-active: 20
        max-wait: 50000
        max-idle: 5
        min-idle: 100


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8080

jwt:
  tokenSignKey: com.xiong
  tokenEcpiration: 660000



#阿里云oss
aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname:




